# Generated by Django 5.0.6 on 2024-08-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="contact_number",
        ),
        migrations.AddField(
            model_name='buyer',
            name='profile',
            field=models.OneToOneField(null=True, blank=True, on_delete=models.CASCADE, to='myapp.Profile'),
        ),
        migrations.AddField(
            model_name="seller",
            name="profile",
            field=models.OneToOneField(null=True, blank=True, on_delete=models.CASCADE, to='myapp.Profile'),
        ),
    ]
