# Generated by Django 5.0.6 on 2024-08-19 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_buyer_profile_alter_seller_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="date_added",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="item_details",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_quote_requested",
        ),
        migrations.RemoveField(
            model_name="product",
            name="location_from",
        ),
        migrations.RemoveField(
            model_name="product",
            name="location_to",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title",
        ),
        migrations.AddField(
            model_name="product",
            name="budget_max",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="budget_min",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="call_preference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="call_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="from_city",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="shifting_plan",
            field=models.CharField(
                choices=[
                    ("7 days", "In next 7 days"),
                    ("15 days", "In next 15 days"),
                    ("30 days", "In next 30 days"),
                    ("30+ days", "In next 30+ days"),
                ],
                default="test",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="specific_requirements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="to_city",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
