# Generated by Django 5.0.6 on 2024-08-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_rename_date_added_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_quote_requested",
            field=models.BooleanField(default=False),
        ),
    ]
