# Generated by Django 5.0.6 on 2024-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_product_is_quote_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="awards",
            field=models.FileField(blank=True, null=True, upload_to="awards/"),
        ),
        migrations.AddField(
            model_name="seller",
            name="company_media",
            field=models.FileField(blank=True, null=True, upload_to="company_media/"),
        ),
        migrations.AddField(
            model_name="seller",
            name="gst_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="poc_contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="poc_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="registered_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="services_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="top_clients",
            field=models.FileField(blank=True, null=True, upload_to="top_clients/"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="key_offerings",
            field=models.TextField(blank=True, null=True),
        ),
    ]
