# Generated by Django 5.0.6 on 2024-08-25 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_seller_awards_seller_company_media_seller_gst_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="key_offerings",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="latest_review",
        ),
    ]
