# Generated by Django 5.0.6 on 2024-08-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_remove_buyer_company_name_remove_seller_company_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="poc_contact",
        ),
        migrations.AddField(
            model_name="seller",
            name="registered_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="gst_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="poc_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="registered_address",
            field=models.TextField(null=True),
        ),
    ]
