# Generated by Django 5.0.6 on 2024-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_remove_seller_poc_contact_seller_registered_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="selected",
            field=models.BooleanField(default=False),
        ),
    ]
