# Generated by Django 5.0.6 on 2024-09-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="call_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seller",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("<10", "<10 employees"),
                    ("10-20", "10-20 employees"),
                    ("20-50", "20-50 employees"),
                    ("50-100", "50-100 employees"),
                    ("100-500", "100-500 employees"),
                    (">500", ">500 employees"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="running_business_since",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="truck_ownership",
            field=models.CharField(
                choices=[
                    ("own", "Own trucks"),
                    ("aggregator", "Aggregator (we do not own trucks)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
