# Generated by Django 4.2.16 on 2024-10-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_seller_call_support_seller_company_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="truck_ownership",
            field=models.CharField(
                choices=[
                    ("Own", "Own trucks"),
                    ("Aggregator", "Aggregator (we do not own trucks)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
